DROP TABLE IF EXISTS PlayersInMatches;
DROP TABLE IF EXISTS MatchEvents;
DROP TABLE IF EXISTS Matches;
DROP TABLE IF EXISTS Players;
DROP TABLE IF EXISTS Teams;
DROP TABLE IF EXISTS TournamentStages;
DROP TABLE IF EXISTS Stadiums;